# Generated by Django 5.1.1 on 2024-10-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_username_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
