# Generated by Django 5.1.1 on 2024-10-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_profile_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='myProfile',
        ),
    ]
