# Generated by Django 5.1.1 on 2024-10-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_rename_profile_myprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
